require 'hashie'
require 'time'
require_relative 'entity/novel'
require_relative 'entity/novel_detail'
require_relative 'entity/author'
require_relative 'entity/category'
require_relative 'entity/sub_category'
